.cache_pip:
  variables:
    FF_USE_FASTZIP: 1
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip_cache"
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - venv
      - .pip_cache

.test_template: &test_template
  stage: test
  before_script:
    - uname -a # Print current OS for debugging
    - pip --version # Print out pip version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - apk update && apk add --no-cache git
    - apk add --no-cache build-base openblas-dev lapack-dev
    - apk add --no-cache hdf5 hdf5-dev
    - apk add --no-cache lzo lzo-dev
    - apk add --no-cache blosc blosc-dev
  script:
    - pip install -e .[dev]
    - python3 -m pytest

pytest/py310:
  image: python:3.10-alpine
  extends: ".cache_pip"
  <<: *test_template

pytest/py311:
  image: python:3.11-alpine
  extends: ".cache_pip"
  <<: *test_template

pytest/py312:
  image: python:3.12-alpine
  extends: ".cache_pip"
  <<: *test_template

pytest/py313:
  image: python:3.13-alpine
  extends: ".cache_pip"
  <<: *test_template

pages:
  image: python:3.12-alpine
  before_script:
    - uname -a # Print current OS for debugging
    - pip --version # Print out pip version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - apt-get build-dep python-tables
  script:
    # Install mkgp package + dependencies using pip
    - pip install -e .[dev,docs]
    # Build the docs and move to public website
    - sphinx-build -b html docs/src/ public/
  artifacts:
    paths:
    - public
  only:
    - main
    - master
    - docker
