cache: &cache
  paths:
    - .cache/pip
    - venv/

.test_template: &test_template
  before_script:
    - uname -a # Print current OS for debugging
    - pip --version # Print out pip version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - apk add --no-cache build-base openblas-dev lapack-dev
    - apk add --no-cache hdf5 hdf5-dev
    - apk add --no-cache cblosc
  script:
    - pip install -e .[dev,demo,gui] # Test with all optional dependencies
    - python3 -m pytest
  stage: test
  cache:
    <<: *cache

py37_test:
  image: python:3.7-alpine
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/py37/.cache/pip"
  <<: *test_template

py38_test:
  image: python:3.8-alpine
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/py38/.cache/pip"
  <<: *test_template

py39_test:
  image: python:3.9-alpine
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/py39/.cache/pip"
  <<: *test_template

py310_test:
  image: python:3.10-alpine
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/py310/.cache/pip"
  <<: *test_template

py311_test:
  image: python:3.11-alpine
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/py311/.cache/pip"
  <<: *test_template

py312_test:
  image: python:3.12-alpine
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/py312/.cache/pip"
  <<: *test_template

pages:
  image: python:3.12-alpine
  before_script:
    - uname -a # Print current OS for debugging
    - pip --version # Print out pip version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - apt-get build-dep python-tables
  script:
    # Install mkgp package + dependencies using pip
    - pip install -e .[dev,docs]
    # Build the docs and move to public website
    - sphinx-build -b html docs/src/ public/
  artifacts:
    paths:
    - public
  only:
    - main
    - master
    - docker
