image: alpine

pages:
  script:
  - apk --no-cache add py2-pip python-dev py2-numpy py2-scipy
  - apk --no-cache --update-cache add gcc gfortran build-base wget freetype-dev libpng-dev openblas-dev #Numpy dependencies
  - pip install sphinx
  - apk --no-cache add make
  - pip install .
  - make -C docs html
  - mv docs/build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
